/** 
	 *************************************   _____   _____   _   _   _   _____   ____   ____   _   _ 
	 ***      Hector Aguilar           *** .|  _  |.| ____|.| | | |.| |.|_   _|.| ___|.|  __|.| |_| |.
	 ***      PHP Developer            *** .|  _  |.|  _  |.| |_| |.| |.  | |  .| _|_ .| |__ .|  _  |.
	 ***      www.aguitech.com         *** .|_| |_|.|_____|.|_____|.|_|.  |_|  .|____|.|____|.|_| |_|.
	 ***      hector@aguitech.com      ***                     by Hector Aguilar [ www.aguitech.com ]
	 *************************************
*/
var $j = jQuery.noConflict();

function divControl3(mostrarDiv){
	if (mostrarDiv) {
		$j(".box3a").show("slow");
		$j(".box3b").show("slow");
		$j(".regresar").show("slow");
		$j(".box1").hide("slow");
		$j(".box2").hide("slow");
		$j(".box4").hide("slow");
		$j(".box5").hide("slow");
		$j(".box6").hide("slow");
		$j(".box7").hide("slow");
		$j(".box8").hide("slow");
		$j(".box9").hide("slow");
		$j(".box10").hide("slow");
		$j(".box11").hide("slow");
		$j(".box12").hide("slow");
		$j(".box13").hide("slow");
		$j(".box14").hide("slow");
		$j(".box15").hide("slow");
		$j(".box16").hide("slow");
		$j(".box17").hide("slow");
		$j(".box18").hide("slow");
		$j(".box19").hide("slow");
		$j(".box20").hide("slow");
		$j(".box21").hide("slow");
		$j(".box22").hide("slow");
		$j(".box23").hide("slow");
		$j(".box24").hide("slow");
	}
}
function divControl6(mostrarDiv){
	if (mostrarDiv) {
		$j(".box6a").show("slow");
		$j(".box6b").show("slow");
		$j(".regresar").show("slow");
		$j(".box1").hide("slow");
		$j(".box2").hide("slow");
		$j(".box3").hide("slow");
		$j(".box4").hide("slow");
		$j(".box5").hide("slow");
		$j(".box7").hide("slow");
		$j(".box8").hide("slow");
		$j(".box9").hide("slow");
		$j(".box10").hide("slow");
		$j(".box11").hide("slow");
		$j(".box12").hide("slow");
		$j(".box13").hide("slow");
		$j(".box14").hide("slow");
		$j(".box15").hide("slow");
		$j(".box16").hide("slow");
		$j(".box17").hide("slow");
		$j(".box18").hide("slow");
		$j(".box19").hide("slow");
		$j(".box20").hide("slow");
		$j(".box21").hide("slow");
		$j(".box22").hide("slow");
		$j(".box23").hide("slow");
		$j(".box24").hide("slow");
	}
}
function divControl7(mostrarDiv){
	if (mostrarDiv) {
		$j(".box7a").show("slow");
		$j(".box7b").show("slow");
		$j(".regresar").show("slow");
		$j(".box1").hide("slow");
		$j(".box2").hide("slow");
		$j(".box3").hide("slow");
		$j(".box4").hide("slow");
		$j(".box5").hide("slow");
		$j(".box6").hide("slow");
		$j(".box8").hide("slow");
		$j(".box9").hide("slow");
		$j(".box10").hide("slow");
		$j(".box11").hide("slow");
		$j(".box12").hide("slow");
		$j(".box13").hide("slow");
		$j(".box14").hide("slow");
		$j(".box15").hide("slow");
		$j(".box16").hide("slow");
		$j(".box17").hide("slow");
		$j(".box18").hide("slow");
		$j(".box19").hide("slow");
		$j(".box20").hide("slow");
		$j(".box21").hide("slow");
		$j(".box22").hide("slow");
		$j(".box23").hide("slow");
		$j(".box24").hide("slow");
	}
}
function divControl10(mostrarDiv){
	if (mostrarDiv) {
		$j(".box10a").show("slow");
		$j(".box10b").show("slow");
		$j(".regresar").show("slow");
		$j(".box1").hide("slow");
		$j(".box2").hide("slow");
		$j(".box3").hide("slow");
		$j(".box4").hide("slow");
		$j(".box5").hide("slow");
		$j(".box6").hide("slow");
		$j(".box7").hide("slow");
		$j(".box8").hide("slow");
		$j(".box9").hide("slow");
		$j(".box11").hide("slow");
		$j(".box12").hide("slow");
		$j(".box13").hide("slow");
		$j(".box14").hide("slow");
		$j(".box15").hide("slow");
		$j(".box16").hide("slow");
		$j(".box17").hide("slow");
		$j(".box18").hide("slow");
		$j(".box19").hide("slow");
		$j(".box20").hide("slow");
		$j(".box21").hide("slow");
		$j(".box22").hide("slow");
		$j(".box23").hide("slow");
		$j(".box24").hide("slow");
	}
}
function divControl14(mostrarDiv){
	if (mostrarDiv) {
		$j(".box14a").show("slow");
		$j(".box14b").show("slow");
		$j(".regresar").show("slow");
		$j(".box1").hide("slow");
		$j(".box2").hide("slow");
		$j(".box3").hide("slow");
		$j(".box4").hide("slow");
		$j(".box5").hide("slow");
		$j(".box6").hide("slow");
		$j(".box7").hide("slow");
		$j(".box8").hide("slow");
		$j(".box9").hide("slow");
		$j(".box10").hide("slow");
		$j(".box11").hide("slow");
		$j(".box12").hide("slow");
		$j(".box13").hide("slow");
		$j(".box15").hide("slow");
		$j(".box16").hide("slow");
		$j(".box17").hide("slow");
		$j(".box18").hide("slow");
		$j(".box19").hide("slow");
		$j(".box20").hide("slow");
		$j(".box21").hide("slow");
		$j(".box22").hide("slow");
		$j(".box23").hide("slow");
		$j(".box24").hide("slow");
	}
}
function divControl17(mostrarDiv){
	if (mostrarDiv) {
		$j(".box17a").show("slow");
		$j(".box17b").show("slow");
		$j(".regresar").show("slow");
		$j(".box1").hide("slow");
		$j(".box2").hide("slow");
		$j(".box3").hide("slow");
		$j(".box4").hide("slow");
		$j(".box5").hide("slow");
		$j(".box6").hide("slow");
		$j(".box7").hide("slow");
		$j(".box8").hide("slow");
		$j(".box9").hide("slow");
		$j(".box10").hide("slow");
		$j(".box11").hide("slow");
		$j(".box12").hide("slow");
		$j(".box13").hide("slow");
		$j(".box14").hide("slow");
		$j(".box15").hide("slow");
		$j(".box16").hide("slow");
		$j(".box18").hide("slow");
		$j(".box19").hide("slow");
		$j(".box20").hide("slow");
		$j(".box21").hide("slow");
		$j(".box22").hide("slow");
		$j(".box23").hide("slow");
		$j(".box24").hide("slow");
	}
}
function divControl21(mostrarDiv){
	if (mostrarDiv) {
		$j(".box21a").show("slow");
		$j(".box21b").show("slow");
		$j(".regresar").show("slow");
		$j(".box1").hide("slow");
		$j(".box2").hide("slow");
		$j(".box3").hide("slow");
		$j(".box4").hide("slow");
		$j(".box5").hide("slow");
		$j(".box6").hide("slow");
		$j(".box7").hide("slow");
		$j(".box8").hide("slow");
		$j(".box9").hide("slow");
		$j(".box10").hide("slow");
		$j(".box11").hide("slow");
		$j(".box12").hide("slow");
		$j(".box13").hide("slow");
		$j(".box14").hide("slow");
		$j(".box15").hide("slow");
		$j(".box16").hide("slow");
		$j(".box17").hide("slow");
		$j(".box18").hide("slow");
		$j(".box19").hide("slow");
		$j(".box20").hide("slow");
		$j(".box22").hide("slow");
		$j(".box23").hide("slow");
		$j(".box24").hide("slow");
	}
}
function divControl24(mostrarDiv){
	if (mostrarDiv) {
		$j(".box24a").show("slow");
		$j(".box24b").show("slow");
		$j(".regresar").show("slow");
		$j(".box1").hide("slow");
		$j(".box2").hide("slow");
		$j(".box3").hide("slow");
		$j(".box4").hide("slow");
		$j(".box5").hide("slow");
		$j(".box6").hide("slow");
		$j(".box7").hide("slow");
		$j(".box8").hide("slow");
		$j(".box9").hide("slow");
		$j(".box10").hide("slow");
		$j(".box11").hide("slow");
		$j(".box12").hide("slow");
		$j(".box13").hide("slow");
		$j(".box14").hide("slow");
		$j(".box15").hide("slow");
		$j(".box16").hide("slow");
		$j(".box17").hide("slow");
		$j(".box18").hide("slow");
		$j(".box19").hide("slow");
		$j(".box20").hide("slow");
		$j(".box21").hide("slow");
		$j(".box22").hide("slow");
		$j(".box23").hide("slow");
	}
}
function divControlz(mostrarDiv){
	if (mostrarDiv) {
		$j(".box1").show("slow");
		$j(".box2").show("slow");
		$j(".box3").show("slow");
		$j(".box4").show("slow");
		$j(".box5").show("slow");
		$j(".box6").show("slow");
		$j(".box7").show("slow");
		$j(".box8").show("slow");
		$j(".box9").show("slow");
		$j(".box10").show("slow");
		$j(".box11").show("slow");
		$j(".box12").show("slow");
		$j(".box13").show("slow");
		$j(".box14").show("slow");
		$j(".box15").show("slow");
		$j(".box16").show("slow");
		$j(".box17").show("slow");
		$j(".box18").show("slow");
		$j(".box19").show("slow");
		$j(".box20").show("slow");
		$j(".box21").show("slow");
		$j(".box22").show("slow");
		$j(".box23").show("slow");
		$j(".box24").show("slow");
		$j(".box3a").hide("slow");
		$j(".box3b").hide("slow");
		$j(".box6a").hide("slow");
		$j(".box6b").hide("slow");
		$j(".box7a").hide("slow");
		$j(".box7b").hide("slow");
		$j(".box10a").hide("slow");
		$j(".box10b").hide("slow");
		$j(".box14a").hide("slow");
		$j(".box14b").hide("slow");
		$j(".box17a").hide("slow");
		$j(".box17b").hide("slow");
		$j(".box21a").hide("slow");
		$j(".box21b").hide("slow");
		$j(".box24a").hide("slow");
		$j(".box24b").hide("slow");
		$j(".regresar").hide("slow");		
	}
}