/** 
	 *************************************   _____   _____   _   _   _   _____   ____   ____   _   _ 
	 ***      Hector Aguilar           *** .|  _  |.| ____|.| | | |.| |.|_   _|.| ___|.|  __|.| |_| |.
	 ***      PHP Developer            *** .|  _  |.|  _  |.| |_| |.| |.  | |  .| _|_ .| |__ .|  _  |.
	 ***      www.aguitech.com         *** .|_| |_|.|_____|.|_____|.|_|.  |_|  .|____|.|____|.|_| |_|.
	 ***      hector@aguitech.com      ***                     by Hector Aguilar [ www.aguitech.com ]
	 *************************************
*/
function divControl3(mostrarDiv){
	if (mostrarDiv) {
		$(".box3a").show("slow");
		$(".box3b").show("slow");
		$(".regresar").show("slow");
		$(".box1").hide("slow");
		$(".box2").hide("slow");
		$(".box4").hide("slow");
		$(".box5").hide("slow");
		$(".box6").hide("slow");
		$(".box7").hide("slow");
		$(".box8").hide("slow");
		$(".box9").hide("slow");
		$(".box10").hide("slow");
		$(".box11").hide("slow");
		$(".box12").hide("slow");
		$(".box13").hide("slow");
		$(".box14").hide("slow");
		$(".box15").hide("slow");
		$(".box16").hide("slow");
		$(".box17").hide("slow");
		$(".box18").hide("slow");
		$(".box19").hide("slow");
		$(".box20").hide("slow");
		$(".box21").hide("slow");
		$(".box22").hide("slow");
		$(".box23").hide("slow");
		$(".box24").hide("slow");
	}
}
function divControl6(mostrarDiv){
	if (mostrarDiv) {
		$(".box6a").show("slow");
		$(".box6b").show("slow");
		$(".regresar").show("slow");
		$(".box1").hide("slow");
		$(".box2").hide("slow");
		$(".box3").hide("slow");
		$(".box4").hide("slow");
		$(".box5").hide("slow");
		$(".box7").hide("slow");
		$(".box8").hide("slow");
		$(".box9").hide("slow");
		$(".box10").hide("slow");
		$(".box11").hide("slow");
		$(".box12").hide("slow");
		$(".box13").hide("slow");
		$(".box14").hide("slow");
		$(".box15").hide("slow");
		$(".box16").hide("slow");
		$(".box17").hide("slow");
		$(".box18").hide("slow");
		$(".box19").hide("slow");
		$(".box20").hide("slow");
		$(".box21").hide("slow");
		$(".box22").hide("slow");
		$(".box23").hide("slow");
		$(".box24").hide("slow");
	}
}
function divControl7(mostrarDiv){
	if (mostrarDiv) {
		$(".box7a").show("slow");
		$(".box7b").show("slow");
		$(".regresar").show("slow");
		$(".box1").hide("slow");
		$(".box2").hide("slow");
		$(".box3").hide("slow");
		$(".box4").hide("slow");
		$(".box5").hide("slow");
		$(".box6").hide("slow");
		$(".box8").hide("slow");
		$(".box9").hide("slow");
		$(".box10").hide("slow");
		$(".box11").hide("slow");
		$(".box12").hide("slow");
		$(".box13").hide("slow");
		$(".box14").hide("slow");
		$(".box15").hide("slow");
		$(".box16").hide("slow");
		$(".box17").hide("slow");
		$(".box18").hide("slow");
		$(".box19").hide("slow");
		$(".box20").hide("slow");
		$(".box21").hide("slow");
		$(".box22").hide("slow");
		$(".box23").hide("slow");
		$(".box24").hide("slow");
	}
}
function divControl10(mostrarDiv){
	if (mostrarDiv) {
		$(".box10a").show("slow");
		$(".box10b").show("slow");
		$(".regresar").show("slow");
		$(".box1").hide("slow");
		$(".box2").hide("slow");
		$(".box3").hide("slow");
		$(".box4").hide("slow");
		$(".box5").hide("slow");
		$(".box6").hide("slow");
		$(".box7").hide("slow");
		$(".box8").hide("slow");
		$(".box9").hide("slow");
		$(".box11").hide("slow");
		$(".box12").hide("slow");
		$(".box13").hide("slow");
		$(".box14").hide("slow");
		$(".box15").hide("slow");
		$(".box16").hide("slow");
		$(".box17").hide("slow");
		$(".box18").hide("slow");
		$(".box19").hide("slow");
		$(".box20").hide("slow");
		$(".box21").hide("slow");
		$(".box22").hide("slow");
		$(".box23").hide("slow");
		$(".box24").hide("slow");
	}
}
function divControl14(mostrarDiv){
	if (mostrarDiv) {
		$(".box14a").show("slow");
		$(".box14b").show("slow");
		$(".regresar").show("slow");
		$(".box1").hide("slow");
		$(".box2").hide("slow");
		$(".box3").hide("slow");
		$(".box4").hide("slow");
		$(".box5").hide("slow");
		$(".box6").hide("slow");
		$(".box7").hide("slow");
		$(".box8").hide("slow");
		$(".box9").hide("slow");
		$(".box10").hide("slow");
		$(".box11").hide("slow");
		$(".box12").hide("slow");
		$(".box13").hide("slow");
		$(".box15").hide("slow");
		$(".box16").hide("slow");
		$(".box17").hide("slow");
		$(".box18").hide("slow");
		$(".box19").hide("slow");
		$(".box20").hide("slow");
		$(".box21").hide("slow");
		$(".box22").hide("slow");
		$(".box23").hide("slow");
		$(".box24").hide("slow");
	}
}
function divControl17(mostrarDiv){
	if (mostrarDiv) {
		$(".box17a").show("slow");
		$(".box17b").show("slow");
		$(".regresar").show("slow");
		$(".box1").hide("slow");
		$(".box2").hide("slow");
		$(".box3").hide("slow");
		$(".box4").hide("slow");
		$(".box5").hide("slow");
		$(".box6").hide("slow");
		$(".box7").hide("slow");
		$(".box8").hide("slow");
		$(".box9").hide("slow");
		$(".box10").hide("slow");
		$(".box11").hide("slow");
		$(".box12").hide("slow");
		$(".box13").hide("slow");
		$(".box14").hide("slow");
		$(".box15").hide("slow");
		$(".box16").hide("slow");
		$(".box18").hide("slow");
		$(".box19").hide("slow");
		$(".box20").hide("slow");
		$(".box21").hide("slow");
		$(".box22").hide("slow");
		$(".box23").hide("slow");
		$(".box24").hide("slow");
	}
}
function divControl21(mostrarDiv){
	if (mostrarDiv) {
		$(".box21a").show("slow");
		$(".box21b").show("slow");
		$(".regresar").show("slow");
		$(".box1").hide("slow");
		$(".box2").hide("slow");
		$(".box3").hide("slow");
		$(".box4").hide("slow");
		$(".box5").hide("slow");
		$(".box6").hide("slow");
		$(".box7").hide("slow");
		$(".box8").hide("slow");
		$(".box9").hide("slow");
		$(".box10").hide("slow");
		$(".box11").hide("slow");
		$(".box12").hide("slow");
		$(".box13").hide("slow");
		$(".box14").hide("slow");
		$(".box15").hide("slow");
		$(".box16").hide("slow");
		$(".box17").hide("slow");
		$(".box18").hide("slow");
		$(".box19").hide("slow");
		$(".box20").hide("slow");
		$(".box22").hide("slow");
		$(".box23").hide("slow");
		$(".box24").hide("slow");
	}
}
function divControl24(mostrarDiv){
	if (mostrarDiv) {
		$(".box24a").show("slow");
		$(".box24b").show("slow");
		$(".regresar").show("slow");
		$(".box1").hide("slow");
		$(".box2").hide("slow");
		$(".box3").hide("slow");
		$(".box4").hide("slow");
		$(".box5").hide("slow");
		$(".box6").hide("slow");
		$(".box7").hide("slow");
		$(".box8").hide("slow");
		$(".box9").hide("slow");
		$(".box10").hide("slow");
		$(".box11").hide("slow");
		$(".box12").hide("slow");
		$(".box13").hide("slow");
		$(".box14").hide("slow");
		$(".box15").hide("slow");
		$(".box16").hide("slow");
		$(".box17").hide("slow");
		$(".box18").hide("slow");
		$(".box19").hide("slow");
		$(".box20").hide("slow");
		$(".box21").hide("slow");
		$(".box22").hide("slow");
		$(".box23").hide("slow");
	}
}
function divControlz(mostrarDiv){
	if (mostrarDiv) {
		$(".box1").show("slow");
		$(".box2").show("slow");
		$(".box3").show("slow");
		$(".box4").show("slow");
		$(".box5").show("slow");
		$(".box6").show("slow");
		$(".box7").show("slow");
		$(".box8").show("slow");
		$(".box9").show("slow");
		$(".box10").show("slow");
		$(".box11").show("slow");
		$(".box12").show("slow");
		$(".box13").show("slow");
		$(".box14").show("slow");
		$(".box15").show("slow");
		$(".box16").show("slow");
		$(".box17").show("slow");
		$(".box18").show("slow");
		$(".box19").show("slow");
		$(".box20").show("slow");
		$(".box21").show("slow");
		$(".box22").show("slow");
		$(".box23").show("slow");
		$(".box24").show("slow");
		$(".box3a").hide("slow");
		$(".box3b").hide("slow");
		$(".box6a").hide("slow");
		$(".box6b").hide("slow");
		$(".box7a").hide("slow");
		$(".box7b").hide("slow");
		$(".box10a").hide("slow");
		$(".box10b").hide("slow");
		$(".box14a").hide("slow");
		$(".box14b").hide("slow");
		$(".box17a").hide("slow");
		$(".box17b").hide("slow");
		$(".box21a").hide("slow");
		$(".box21b").hide("slow");
		$(".box24a").hide("slow");
		$(".box24b").hide("slow");
		$(".regresar").hide("slow");		
	}
}