<!DOCTYPE html>
<html>
	<head>
		<title>Hola</title>
	</head>
	<body>
		<h1>ABCDEFGHIJKLMNOPQRSTUVWXYZ</h1>
		<h2>ABCDEFGHIJKLMNOPQRSTUVWXYZ</h2>
		<h3>ABCDEFGHIJKLMNOPQRSTUVWXYZ</h3>
		<h4>ABCDEFGHIJKLMNOPQRSTUVWXYZ</h4>
		<h5>ABCDEFGHIJKLMNOPQRSTUVWXYZ</h5>
		<h6>ABCDEFGHIJKLMNOPQRSTUVWXYZ</h6>
		<div onclick="">ABCDEFGHIJKLMNOPQRSTUVWXYZ</div>
		<p onclick="">ABCDEFGHIJKLMNOPQRSTUVWXYZ</p>
		<a href="" onclick="">ABCDEFGHIJKLMNOPQRSTUVWXYZ</a>
		<ul>
			<li>ABCDEFGHIJKLMNOPQRSTUVWXYZ</li>
			<li>ABCDEFGHIJKLMNOPQRSTUVWXYZ</li>
			<li>ABCDEFGHIJKLMNOPQRSTUVWXYZ</li>
		</ul>
		<ol>
			<li>ABCDEFGHIJKLMNOPQRSTUVWXYZ</li>
			<li>ABCDEFGHIJKLMNOPQRSTUVWXYZ</li>
			<li>ABCDEFGHIJKLMNOPQRSTUVWXYZ</li>
		</ol>
		<span>ABCDEFGHIJKLMNOPQRSTUVWXYZ</span>
		<i>ABCDEFGHIJKLMNOPQRSTUVWXYZ</i>
		
	</body>
</html>